flags: {}
extra-include-dirs:
- /usr/local/include
extra-package-dbs: []
extra-lib-dirs:
- /usr/local/lib
packages:
- .
- location:
    git: https://github.com/DAHeath/z3-haskell
    commit: bb02352e19fc67d8fc7489c4ea0bd3cb609e1b3e
  extra-dep: true
extra-deps:
resolver: lts-11.4
